# Generated by Django 3.0.4 on 2020-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doodle', models.ImageField(upload_to='')),
                ('redesign', models.IntegerField()),
                ('receiver', models.CharField(max_length=20)),
                ('r_phone_num', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=100)),
                ('base_address', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=20)),
                ('o_phone_num', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('star', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
